[database]
name="postgresql"
host="localhost"
port=5432
dbName="db_cheatsheet"
username="budi"
password="budibodonk"
connectionString="postgresql://budi:budibodonk@localhost/db_cheatsheet"

[log]
logPath="/path/to/logfile.log"